{% set version = "1.3.0" %}
{% set name = "anaconda-opentelemetry" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/anaconda/anaconda-otel-python/archive/refs/tags/v{{ version }}.tar.gz
  sha256: abe5b5dfdf621ee1d04d21431dccd836d96400f975c0499139dcb2ffe6fa28b8

build:
  number: 0
  skip: True  # [py<310]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - python
    - pip
    - setuptools >=61.0
    - wheel
  run:
    - python
    # To point to conda-recipe/meta.yaml
    # https://github.com/anaconda/anaconda-otel-python/blob/v1.3.0/conda-recipe/meta.yaml#L23
    # pyproject.toml does not specify all dependency.
    - anaconda-anon-usage
    - opentelemetry-api >=1.40.0,<1.44
    - opentelemetry-sdk >=1.40.0,<1.44
    - opentelemetry-exporter-otlp-proto-grpc >=1.40.0,<1.44
    - opentelemetry-exporter-otlp-proto-http >=1.40.0,<1.44
    - grpcio >=1.71.0
    - requests >=2.32.5

test:
  imports:
    - anaconda_opentelemetry
  source_files:
    - tests/
  requires:
    - pip
    - pytest
    - flask
    - conda
  commands:
    - pip check
    - set OTEL_USE_CONSOLE_EXPORTER=TRUE # [win]
    - export OTEL_USE_CONSOLE_EXPORTER=TRUE # [unix]
    # import _overlapped fails with OSError: [WinError 10106] on Windows
    # This may be due to how the tests are run. 
    - python -m pytest ./tests -k "not (test_export_errors_print or test_export_errors_silenced)"

about:
  home: https://github.com/anaconda/anaconda-otel-python
  summary: "An OpenTelemetry wrapper for Anaconda application telemetry"
  description: |
    Anaconda's OpenTelemetry Instrumentation Libraries
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  dev_url: https://github.com/anaconda/anaconda-otel-python
  doc_url: https://github.com/anaconda/anaconda-otel-python
